# Generated by Django 2.2.7 on 2019-11-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('photo_url', models.TextField(default='n/a')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('age', models.IntegerField(default=0)),
                ('breed', models.CharField(default='n/a', max_length=101)),
                ('photo_url', models.TextField(default='n/a')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='dog.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk', models.CharField(default='n/a', max_length=100)),
                ('eat', models.CharField(default='n/a', max_length=100)),
                ('poop', models.CharField(default='n/a', max_length=101)),
                ('pee', models.CharField(default='n/a', max_length=100)),
                ('medicine', models.CharField(default='n/a', max_length=100)),
                ('dog', models.ForeignKey(default='n/a', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dog.Dog')),
            ],
        ),
    ]
